// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokKartiProjesi.Data;

#nullable disable

namespace StokKartiProjesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220318082839_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StokKartiProjesi.Models.Satis", b =>
                {
                    b.Property<int>("SatisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatisID"), 1L, 1);

                    b.Property<int>("BirimFiyatı")
                        .HasColumnType("int");

                    b.Property<string>("IslemTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<string>("StokID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamFiyat")
                        .HasColumnType("int");

                    b.HasKey("SatisID");

                    b.HasIndex("StokID");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("StokKartiProjesi.Models.Stok", b =>
                {
                    b.Property<string>("StokID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Fiyat1")
                        .HasColumnType("real");

                    b.Property<float>("Fiyat2")
                        .HasColumnType("real");

                    b.Property<float>("Fiyat3")
                        .HasColumnType("real");

                    b.Property<float>("Fiyat4")
                        .HasColumnType("real");

                    b.Property<float>("Fiyat5")
                        .HasColumnType("real");

                    b.Property<float>("KDV")
                        .HasColumnType("real");

                    b.Property<string>("StokAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokBarkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StokID");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("StokKartiProjesi.Models.Satis", b =>
                {
                    b.HasOne("StokKartiProjesi.Models.Stok", "Stok")
                        .WithMany("Satis")
                        .HasForeignKey("StokID");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("StokKartiProjesi.Models.Stok", b =>
                {
                    b.Navigation("Satis");
                });
#pragma warning restore 612, 618
        }
    }
}
